# Generated by Django 3.1 on 2021-10-10 10:04

import colorfield.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0004_auto_20211010_1004'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter ingredient name', max_length=150, unique=True, verbose_name='Ingredient name')),
                ('measurement_unit', models.CharField(help_text='Enter measurement unit', max_length=25, verbose_name='Measurement unit')),
            ],
            options={
                'verbose_name': 'Ingredient',
                'verbose_name_plural': 'Ingredients',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter recipe name', max_length=150, unique=True, verbose_name='Recipe name')),
                ('image', models.ImageField(help_text='Enter recipe image', upload_to='recipes/images/', verbose_name='Image')),
                ('text', models.TextField(help_text='Give recipe description', verbose_name='Text')),
                ('cooking_time', models.PositiveSmallIntegerField(help_text='Add cooking time in minutes', verbose_name='Cooking time')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('author', models.ForeignKey(help_text='Enter recipe author', on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to=settings.AUTH_USER_MODEL, verbose_name='Follower')),
            ],
            options={
                'verbose_name': 'Recipe',
                'verbose_name_plural': 'Recipes',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Add tag name', max_length=150, unique=True, verbose_name='Tag name')),
                ('colour', colorfield.fields.ColorField(default='#FFFFFF', help_text='Add tag color', max_length=18, unique=True, verbose_name='Tag color')),
                ('slug', models.SlugField(help_text='Add slug', unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ('name', 'slug'),
            },
        ),
        migrations.CreateModel(
            name='UserFavorites',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='favorites', serialize=False, to='users.user')),
                ('recipes', models.ManyToManyField(to='recipes.Recipe')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveSmallIntegerField(help_text='Enter amount', verbose_name='Amount')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ingredient', models.ForeignKey(help_text='Enter ingredient', on_delete=django.db.models.deletion.CASCADE, to='recipes.ingredient', verbose_name='Ingredient')),
                ('recipe', models.ForeignKey(help_text='Enter recipe', on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='recipes.recipe', verbose_name='Recipe')),
            ],
            options={
                'verbose_name': 'Recipe ingredient',
                'verbose_name_plural': 'Recipe ingredients',
                'ordering': ('-created',),
            },
        ),
        migrations.AddField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(db_index=True, help_text='Add recipe tags', to='recipes.Tag', verbose_name='Tags'),
        ),
        migrations.AddConstraint(
            model_name='recipeingredient',
            constraint=models.UniqueConstraint(fields=('recipe', 'ingredient'), name='unique_ingredients'),
        ),
    ]
