# Generated by Django 3.1 on 2021-10-16 13:55

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteRecipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'User favorite recipe',
                'verbose_name_plural': 'User favorite recipes',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter ingredient name', max_length=150, unique=True, verbose_name='Ingredient name')),
                ('measurement_unit', models.CharField(help_text='Enter measurement unit', max_length=25, verbose_name='Measurement unit')),
            ],
            options={
                'verbose_name': 'Ingredient',
                'verbose_name_plural': 'Ingredients',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter recipe name', max_length=150, unique=True, verbose_name='Recipe name')),
                ('image', models.ImageField(help_text='Enter recipe image', upload_to='recipes/images/', verbose_name='Image')),
                ('text', models.TextField(help_text='Give recipe description', verbose_name='Text')),
                ('cooking_time', models.PositiveSmallIntegerField(help_text='Add cooking time in minutes', verbose_name='Cooking time, min')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Recipe',
                'verbose_name_plural': 'Recipes',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveSmallIntegerField(help_text='Enter amount', verbose_name='Amount')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Recipe ingredient',
                'verbose_name_plural': 'Recipe ingredients',
                'ordering': ('recipe', 'ingredient'),
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Add tag name', max_length=150, unique=True, verbose_name='Tag name')),
                ('color', colorfield.fields.ColorField(default='#FFFFFF', help_text='Add tag color', max_length=18, unique=True, verbose_name='Tag color')),
                ('slug', models.SlugField(help_text='Add slug', unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ('name', 'slug'),
            },
        ),
    ]
