# Generated by Django 3.1 on 2021-10-11 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20211011_1311'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipeingredient',
            options={'ordering': ('ingredient__id', '-created'), 'verbose_name': 'Recipe ingredient', 'verbose_name_plural': 'Recipe ingredients'},
        ),
    ]
