# Generated by Django 3.1 on 2021-10-16 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20211016_1413'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userfavorites',
            options={'ordering': ('user',), 'verbose_name': 'User favorite recipe', 'verbose_name_plural': 'User favorite recipes'},
        ),
    ]
