# Generated by Django 3.1 on 2021-10-11 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20211011_1540'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipeingredient',
            options={'ordering': ('recipe', '-created'), 'verbose_name': 'Recipe ingredient', 'verbose_name_plural': 'Recipe ingredients'},
        ),
    ]
