# Generated by Django 3.1 on 2021-10-16 15:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_auto_20211016_1415'),
        ('recipes', '0005_auto_20211016_1413'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingCartRecipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='recipes.recipe', verbose_name='Recipe')),
            ],
            options={
                'verbose_name': 'Shopping cart recipe',
                'verbose_name_plural': 'Shopping cart recipes',
                'ordering': ('id',),
            },
        ),
        migrations.AlterField(
            model_name='userfavorites',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='favorites', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.CreateModel(
            name='UserShoppingCart',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='shopping_cart', serialize=False, to='users.user', verbose_name='User')),
                ('recipes', models.ManyToManyField(through='recipes.ShoppingCartRecipe', to='recipes.Recipe')),
            ],
            options={
                'verbose_name': 'User shopping cart',
                'ordering': ('user',),
            },
        ),
        migrations.AddField(
            model_name='shoppingcartrecipe',
            name='shopping_cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='recipes.usershoppingcart', verbose_name='Shopping cart'),
        ),
        migrations.AddConstraint(
            model_name='shoppingcartrecipe',
            constraint=models.UniqueConstraint(fields=('shopping_cart', 'recipe'), name='unique_recipe_for_shopping_cart'),
        ),
    ]
