# Generated by Django 3.1 on 2021-10-11 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20211011_1541'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ('id',), 'verbose_name': 'Recipe', 'verbose_name_plural': 'Recipes'},
        ),
    ]
