# Generated by Django 3.1 on 2021-10-16 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('id',), 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
