# Generated by Django 3.1 on 2021-10-13 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='follow',
            options={'ordering': ('id',), 'verbose_name': 'Follow', 'verbose_name_plural': 'Follows'},
        ),
    ]
