# Generated by Django 3.1 on 2021-10-07 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20211007_1934'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='follow',
            table=None,
        ),
    ]
